# Generated by Django 5.0 on 2024-01-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_project_author_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
